// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kahoouotopridrpufgub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthaG9vdW90b3ByaWRycHVmZ3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODQ5ODUsImV4cCI6MjA2NzQ2MDk4NX0.G7r-LaUyLFgg7hMh4ufI_2X_P6VcLfrYnCHNRqvxYgg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});